typography_spectrum: 0.30872
color:
  brandColors:
    - '#1f1a17'
    - '#d2b057'
    - '#ffffff'
    - '#9c9897'
    - '#d9d8d6'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.87813
analytics:
  google: UA-373256-8
  facebook: null
  twitter: null
name: Ap1
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Apartamento 101
content: []
description: ''
purpose: []
url: 'https://ap1.com.br/'
author:
  name: Gustavo Oliveira
  email: cetres@gmail.com
