name: Ap1
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30872
title: Apartamento 101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-373256-8
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1a17'
    - '#d2b057'
    - '#ffffff'
    - '#9c9897'
    - '#d9d8d6'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: 793ac29a-fa4c-404a-a461-484ab7ff467f
    url: null
