name: Ap1
favicon: null
layout_spectrum: 0.8
title: Apartamento 101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-373256-8
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 793ac29a-fa4c-404a-a461-484ab7ff467f
    url: null
